
services:
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 60 1 --loglevel warning --requirepass J_p#A.b1997
    volumes: 
      - ./FreshFood/Infrastructure/Redis:/data
      
  sql-server:
    image: mcr.microsoft.com/mssql/server
    container_name: sql-server
    environment:
      - MSSQL_SA_PASSWORD=J_p#A.b1997
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - ./FreshFood/Infrastructure/Scripts/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
  
  elasticsearch:
   container_name: elasticsearch
   image: docker.elastic.co/elasticsearch/elasticsearch:8.14.3
   ports:
    - 9200:9200
   volumes:
    - elasticsearch-data:/usr/share/elasticsearch/data
   environment:
    - xpack.security.enabled=false
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    - discovery.type=single-node
   networks:
    - monitoring
  
  kibana:
   container_name: kibana
   image: docker.elastic.co/kibana/kibana:8.14.3
   ports:
    - 5601:5601
   depends_on:
    - elasticsearch
   environment:
    - ELASTICSEARCH_URL=http://localhost:9200
    - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
   networks:
    - monitoring
  
networks:
  monitoring:
    driver: bridge

volumes:
  elasticsearch-data: